<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="i18n\*.i18n.json"/>
        <AdditionalFiles Include="i18n\*.i18n.yaml"/>
        <AdditionalFiles Include="slang.json"/>
    </ItemGroup>

    <ItemGroup>
        <!--        <ProjectReference Include="..\..\Slang.Net\Slang.Net.csproj" />-->
        <ProjectReference Include="..\..\Slang.Net\Slang.Net.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <!--    <ItemGroup>-->
    <!--        <PackageReference Include="Slang.Net" Version="9.2.0" />-->
    <!--    </ItemGroup>-->

</Project>
