<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="i18n\*.i18n.json" />
        <AdditionalFiles Include="slang.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Slang.Net" Version="9.0.0" />
    </ItemGroup>

</Project>
