<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks />
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="i18n\*.i18n.json" />
        <AdditionalFiles Include="slang.json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Slang\Slang.csproj" />
        <ProjectReference Include="..\..\Slang.Generator\Slang.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\Slang.Generator.Core\Slang.Generator.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\Slang.Shared\Slang.Shared.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
