<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks />
        <TargetFramework>net9.0</TargetFramework>
        
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Slang.Gpt\Slang.Gpt.csproj" />
    </ItemGroup>

</Project>
