<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Version>1.1.1.0</Version>

        <IsPackable>true</IsPackable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>slang</ToolCommandName>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Gpt\Slang.Gpt\Slang.Gpt.csproj" />
        <ProjectReference Include="..\..\Slang.Utilities.Core\Slang.Utilities.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Slang.Net" />
        <PackageReference Include="System.CommandLine" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="i18n\*.i18n.json" />
        <AdditionalFiles Include="slang.json" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" Visible="false" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

</Project>
