<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <RoslynVersion>4</RoslynVersion>
        <DefineConstants>$(DefineConstants);ROSLYN4_0_OR_GREATER</DefineConstants>

        <LangVersion>preview</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <!-- Make sure that ResolveProjectReferences target runs before pack to include Jab for roslyn3. -->
        <!--        <BeforePack>$(BeforePack);ResolveProjectReferences</BeforePack>-->
        <!--        <BuildProjectReferences Condition="'$(NoBuild)' == 'true'">false</BuildProjectReferences>-->
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>

        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
        <PackageReference Include="System.Text.Json" Version="9.0.11" PrivateAssets="all" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" PrivateAssets="all" GeneratePathProperty="true" />
        <PackageReference Include="YamlDotNet.System.Text.Json" Version="1.7.1" PrivateAssets="all" GeneratePathProperty="true" />
        <!--        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" GeneratePathProperty="true" PrivateAssets="all" />-->
    </ItemGroup>

    <!--    <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">-->
    <!--        <PackageReference Include="System.Text.Json" Version="8.0.5" PrivateAssets="all" />-->
    <!--    </ItemGroup>-->

    <ItemGroup>
        <!-- Package the generator in the analyzer directory of the nuget package -->
        <!--        <None Include="$(OutputPath)\netstandard2.0\$(AssemblyName).dll"-->
        <!--            PackagePath="analyzers/dotnet/roslyn4.0/cs" -->
        <!--            Pack="true" Visible="false" />-->
        <!--        <None Include="$(OutputPath)\netstandard2.0\$(AssemblyName).dll"-->
        <!--            PackagePath="analyzers/dotnet/roslyn4.12/cs"-->
        <!--            Pack="true" Visible="false" />-->
        <None Include="$(OutputPath)\netstandard2.0\$(AssemblyName).dll" PackagePath="analyzers\dotnet\roslyn4.0\cs" Pack="true" Visible="false" />
        <None Include="$(OutputPath)\netstandard2.0\$(AssemblyName).dll" PackagePath="analyzers\dotnet\roslyn4.12\cs" Pack="true" Visible="false" />

        <None Include="$(OutputPath)\netstandard2.0\System.Text.Json.dll" PackagePath="analyzers/dotnet/roslyn4.0/cs" Pack="true" Visible="false" />
        <None Include="$(OutputPath)\netstandard2.0\System.Text.Json.dll" PackagePath="analyzers/dotnet/roslyn4.12/cs" Pack="true" Visible="false" />

        <Content Include="build\Slang.Net.targets" Pack="True" PackagePath="build" />
    </ItemGroup>

    <!--    <PropertyGroup>-->
    <!--        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>-->
    <!--    </PropertyGroup>-->


    <!--    <Target Name="GetDependencyTargetPaths">-->
    <!--        <ItemGroup>-->
    <!--            <TargetPathWithTargetPlatformMoniker Include="$(OutputPath)\netstandard2.0\System.Text.Json.dll" IncludeRuntimeDependency="false" />-->
    <!--        </ItemGroup>-->
    <!--    </Target>-->

    <!--    <Target Name="GetDependencyTargetPaths">-->
    <!--        <ItemGroup>-->
    <!--            <TargetPathWithTargetPlatformMoniker Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\*.dll" IncludeRuntimeDependency="false" />-->
    <!--        </ItemGroup>-->
    <!--    </Target>-->

    <ItemGroup>
        <None Include="..\README.md" Pack="true" Visible="false" PackagePath="\" />
        <None Include="..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <!--    <ItemGroup>-->
    <!--        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />-->
    <!--    </ItemGroup>-->
    
    <!-- See https://github.com/dotnet/roslyn-sdk/blob/0313c80ed950ac4f4eef11bb2e1c6d1009b328c4/samples/CSharp/SourceGenerators/SourceGeneratorSamples/SourceGeneratorSamples.csproj#L13-L30
    and https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145 -->
    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>

    <Target Name="GetDependencyTargetPaths">
        <!-- Manually include the DLL of each NuGet package that this analyzer uses. -->
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker Include="$(PKGYamlDotNet)\lib\netstandard2.0\YamlDotNet.dll" IncludeRuntimeDependency="false" />
            <TargetPathWithTargetPlatformMoniker Include="$(PKGYamlDotNet_System_Text_Json)\lib\netstandard2.0\YamlDotNet.System.Text.Json.dll" IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>

    <Import Project="Slang.Common.props" />

    <ItemGroup>
        <InternalsVisibleTo Include="Slang.Tests"/>
    </ItemGroup>
</Project>
