<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks />
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Slang.Generator.Core\Slang.Generator.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>

</Project>
