<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;</TargetFrameworks>
        <IsPackable>true</IsPackable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Slang</RootNamespace>
        <DefineConstants>$(DefineConstants);SLANG_ATTRIBUTES_PACKAGE</DefineConstants>
        <Version>9.3.0</Version>
        <Version Condition="'$(ReleaseVersion)' != ''">$(ReleaseVersion)</Version>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" Visible="false" PackagePath="\" />
        <None Include="..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Slang.Net\Attributes.cs">
            <Link>Attributes.cs</Link>
        </Compile>
    </ItemGroup>

</Project>
