<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\..\Slang.Shared\Slang.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" />
        <PackageReference Include="OneOf" />
        <PackageReference Include="OneOf.SourceGenerator" />
        <PackageReference Include="Project2015To2017" />
    </ItemGroup>
</Project>
