<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>

        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifestfest>app.manifest</ApplicationManifestfest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">none</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="CommunityToolkit.Mvvm" />

        <PackageReference Include="Slang.Net" />

    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="slang.json" />
        <AdditionalFiles Include="i18n\*.i18n.json" />
    </ItemGroup>
    
</Project>
